-- =============================================================================
--  T-share · Supabase schema
-- =============================================================================
--  Replaces the MySQL database behind the Laravel API (t-share-back) and the
--  Angular front (t-share-front).
--
--  Conventions
--    * Every table is prefixed `tshare_` — the Supabase project is shared with
--      other apps, so the prefix is what keeps the namespace clean.
--    * Column names are English and normalised; `db/legacy-map.ts` records the
--      Spanish column each one came from.
--    * Access is service-role only (no Supabase Auth, no RLS). The Next.js
--      server is the single writer; nothing here is reachable from a browser.
--    * Legacy integer ids are preserved so every foreign key in the CSV export
--      still resolves. Identity sequences are re-seeded at the end of the load.
--
--  Files live in S3 (the bucket is NOT migrated). Two columns carry them:
--    * `*_key`  — S3 object key, as written by the old Laravel app. Private
--                 objects; the app signs a temporary URL on read.
--    * `*_url`  — absolute URL, written by new uploads.
--  A row has one or the other; `src/lib/storage.ts` resolves both to a URL.
-- =============================================================================

begin;

-- Case-insensitive email columns, so a login never depends on how the address
-- was typed. Supabase ships the extension; this only enables it.
create extension if not exists citext;

-- Trigram indexes, so the activity search stays fast as the catalogue grows.
create extension if not exists pg_trgm;

-- -----------------------------------------------------------------------------
-- Reference data
-- -----------------------------------------------------------------------------

create table if not exists tshare_countries (
  id          bigint generated by default as identity primary key,
  name        text not null,
  nationality text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_countries is 'Legacy: paises';

create table if not exists tshare_labels (
  id          bigint generated by default as identity primary key,
  key         text not null,
  label       text not null,
  country_id  bigint references tshare_countries (id) on delete cascade,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_labels is 'Legacy: labels — per-country UI wording (nombre -> key)';
create index if not exists tshare_labels_country_idx on tshare_labels (country_id);
create unique index if not exists tshare_labels_country_key_uidx on tshare_labels (country_id, key);

create table if not exists tshare_roles (
  id         bigint generated by default as identity primary key,
  name       text not null,
  slug       text not null,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table tshare_roles is 'Legacy: roles (rols) — guard_name -> slug';
create unique index if not exists tshare_roles_slug_uidx on tshare_roles (slug);

create table if not exists tshare_grades (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  deleted_at  timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_grades is 'Legacy: cursos — age range / school level';

create table if not exists tshare_subjects (
  id         bigint generated by default as identity primary key,
  name       text not null,
  image      text,
  country_id bigint references tshare_countries (id) on delete set null,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table tshare_subjects is 'Legacy: ramos';
create index if not exists tshare_subjects_country_idx on tshare_subjects (country_id);

create table if not exists tshare_subject_equivalences (
  id                bigint generated by default as identity primary key,
  equivalence_group int not null,
  subject_id        bigint not null references tshare_subjects (id) on delete cascade,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
comment on table tshare_subject_equivalences is
  'Legacy: equivalencias — groups subjects that mean the same across countries';
create index if not exists tshare_subject_equivalences_group_idx
  on tshare_subject_equivalences (equivalence_group);

create table if not exists tshare_subject_grades (
  id         bigint generated by default as identity primary key,
  subject_id bigint references tshare_subjects (id) on delete cascade,
  grade_id   bigint references tshare_grades (id) on delete cascade,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table tshare_subject_grades is 'Legacy: ramos_cursos — a subject taught at a grade';
create index if not exists tshare_subject_grades_subject_idx on tshare_subject_grades (subject_id);
create index if not exists tshare_subject_grades_grade_idx on tshare_subject_grades (grade_id);

create table if not exists tshare_units (
  id               bigint generated by default as identity primary key,
  name             text not null,
  description      text,
  subject_grade_id bigint references tshare_subject_grades (id) on delete set null,
  deleted_at       timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
comment on table tshare_units is 'Legacy: unidades — curriculum unit inside a subject/grade';
create index if not exists tshare_units_subject_grade_idx on tshare_units (subject_grade_id);

create table if not exists tshare_skills (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_skills is
  'Legacy: habilidades — 21st-century skills catalogue. The legacy actividad_id was always NULL and is dropped.';

create table if not exists tshare_sections (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  position    int not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_sections is
  'Legacy: secciones — moments of the class (Inicio / Desarrollo / Cierre). The legacy actividad_id was always NULL and is dropped.';

create table if not exists tshare_resource_types (
  id         bigint generated by default as identity primary key,
  name       text not null,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table tshare_resource_types is 'Legacy: tipo_recurso';

create table if not exists tshare_suggested_materials (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_suggested_materials is 'Legacy: materiales_sugeridos — autocomplete list';

create table if not exists tshare_schools (
  id          bigint generated by default as identity primary key,
  name        text not null,
  address     text,
  rbd         int,
  region_code int,
  commune     text,
  deleted_at  timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_schools is 'Legacy: colegios — rbd is the Chilean school registry number';
create index if not exists tshare_schools_name_idx on tshare_schools (name);

-- -----------------------------------------------------------------------------
-- Users
-- -----------------------------------------------------------------------------

create table if not exists tshare_users (
  id                      bigint generated by default as identity primary key,
  first_name              text not null default '',
  last_name               text,
  email                   citext not null,
  email_verified_at       timestamptz,

  -- Auth. Migrated rows carry the Laravel bcrypt hash ($2y$); the app verifies
  -- it, then forces a reset so the hash is rewritten under this app's cost.
  password_hash           text not null,
  must_change_password    boolean not null default false,
  last_login_at           timestamptz,
  login_attempts          int not null default 0,
  remember_token          text,

  -- Profile
  bio                     text,
  audience                text,
  gender                  text,
  birth_date              date,
  national_id             text,
  country_id              bigint references tshare_countries (id) on delete set null,
  country_name            text,
  region                  text,
  website_url             text,
  youtube_url             text,
  twitter_url             text,
  facebook_url            text,
  instagram_url           text,
  avatar_key              text,
  avatar_url              text,

  -- Account state
  is_active               boolean not null default false,
  is_verified             boolean not null default false,
  profile_completed       boolean not null default false,
  activation_code         text,
  activation_expires_on   date,
  subscription_expires_at timestamptz,
  remaining_days          int,

  deleted_at              timestamptz,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);
comment on table tshare_users is 'Legacy: users — name -> first_name, apellido -> last_name, descripcion -> bio';
comment on column tshare_users.gender is
  'Raw legacy value. Mostly the codes 1/2/3 the old form wrote; a handful of rows are free text.';
comment on column tshare_users.must_change_password is
  'True for every migrated account: the Laravel hash is accepted once, then the user must set a new password.';
create unique index if not exists tshare_users_email_uidx on tshare_users (email);
create index if not exists tshare_users_country_idx on tshare_users (country_id);
create index if not exists tshare_users_deleted_idx on tshare_users (deleted_at);

create table if not exists tshare_password_resets (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references tshare_users (id) on delete cascade,
  token_hash text not null,
  expires_at timestamptz not null,
  used_at    timestamptz,
  created_at timestamptz not null default now()
);
comment on table tshare_password_resets is
  'Replaces Laravel password_resets. Stores a SHA-256 of the emailed token, never the token.';
create unique index if not exists tshare_password_resets_token_uidx
  on tshare_password_resets (token_hash);
create index if not exists tshare_password_resets_user_idx on tshare_password_resets (user_id);

create table if not exists tshare_user_roles (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references tshare_users (id) on delete cascade,
  role_id    bigint not null references tshare_roles (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table tshare_user_roles is 'Legacy: roles_users';
create unique index if not exists tshare_user_roles_uidx on tshare_user_roles (user_id, role_id);

create table if not exists tshare_school_users (
  id         bigint generated by default as identity primary key,
  school_id  bigint not null references tshare_schools (id) on delete cascade,
  user_id    bigint not null references tshare_users (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table tshare_school_users is 'Legacy: colegios_users';
create unique index if not exists tshare_school_users_uidx on tshare_school_users (school_id, user_id);
create index if not exists tshare_school_users_user_idx on tshare_school_users (user_id);

create table if not exists tshare_user_subjects (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references tshare_users (id) on delete cascade,
  subject_id bigint not null references tshare_subjects (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table tshare_user_subjects is 'Legacy: ramos_users — subjects a teacher teaches';
create unique index if not exists tshare_user_subjects_uidx on tshare_user_subjects (user_id, subject_id);

create table if not exists tshare_user_grades (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references tshare_users (id) on delete cascade,
  grade_id   bigint not null references tshare_grades (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table tshare_user_grades is 'Legacy: users_cursos';
create unique index if not exists tshare_user_grades_uidx on tshare_user_grades (user_id, grade_id);

create table if not exists tshare_user_skills (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references tshare_users (id) on delete cascade,
  skill_id   bigint not null references tshare_skills (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table tshare_user_skills is 'Legacy: users_habilidades';
create unique index if not exists tshare_user_skills_uidx on tshare_user_skills (user_id, skill_id);

create table if not exists tshare_user_groups (
  id         bigint generated by default as identity primary key,
  name       text,
  user_id    bigint not null references tshare_users (id) on delete cascade,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table tshare_user_groups is 'Legacy: user_grupos';
create index if not exists tshare_user_groups_user_idx on tshare_user_groups (user_id);

create table if not exists tshare_follows (
  id          bigint generated by default as identity primary key,
  follower_id bigint not null references tshare_users (id) on delete cascade,
  followed_id bigint not null references tshare_users (id) on delete cascade,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint tshare_follows_not_self check (follower_id <> followed_id)
);
comment on table tshare_follows is 'Legacy: seguidores — user_id follows seguido_id';
create unique index if not exists tshare_follows_uidx on tshare_follows (follower_id, followed_id);
create index if not exists tshare_follows_followed_idx on tshare_follows (followed_id);

-- -----------------------------------------------------------------------------
-- Activities
-- -----------------------------------------------------------------------------

create table if not exists tshare_activities (
  id                 bigint generated by default as identity primary key,
  title              text not null,
  learning_objective text,
  description        text,
  evaluation         text,
  duration_minutes   int,
  rating             numeric(3, 2),
  cover_image_key    text,
  cover_image_url    text,
  pdf_key            text,
  pdf_url            text,
  -- Denormalised so the "más usadas" ordering is an index scan rather than a
  -- join and a group-by. Kept current by the triggers further down, and
  -- recomputed from scratch by tshare_refresh_activity_counters().
  saved_count        int not null default 0,
  download_count     int not null default 0,
  user_id            bigint not null references tshare_users (id) on delete cascade,
  deleted_at         timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
comment on table tshare_activities is
  'Legacy: actividades — nombre -> title, objetivos -> learning_objective, avatar -> cover_image_key, puntaje -> rating.';
comment on column tshare_activities.cover_image_key is
  'Legacy avatar_public duplicated avatar for every row that had one, so it is not carried over.';
create index if not exists tshare_activities_user_idx on tshare_activities (user_id);
create index if not exists tshare_activities_created_idx on tshare_activities (created_at desc);
create index if not exists tshare_activities_deleted_idx on tshare_activities (deleted_at);
-- Search is a substring match across the three text columns (see
-- `searchActivities` in src/lib/activities.ts), which a trigram index serves
-- directly — a tsvector index would not be used by `ilike '%…%'`.
create index if not exists tshare_activities_title_trgm_idx
  on tshare_activities using gin (title gin_trgm_ops);
create index if not exists tshare_activities_objective_trgm_idx
  on tshare_activities using gin (learning_objective gin_trgm_ops);

create table if not exists tshare_activity_subject_grades (
  id               bigint generated by default as identity primary key,
  activity_id      bigint not null references tshare_activities (id) on delete cascade,
  subject_grade_id bigint not null references tshare_subject_grades (id) on delete cascade,
  deleted_at       timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
comment on table tshare_activity_subject_grades is
  'Legacy: actividades_ramos_cursos — which subject/grade an activity targets';
create index if not exists tshare_activity_subject_grades_activity_idx
  on tshare_activity_subject_grades (activity_id);
create index if not exists tshare_activity_subject_grades_sg_idx
  on tshare_activity_subject_grades (subject_grade_id);

create table if not exists tshare_activity_units (
  id          bigint generated by default as identity primary key,
  activity_id bigint not null references tshare_activities (id) on delete cascade,
  unit_id     bigint not null references tshare_units (id) on delete cascade,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_activity_units is 'Legacy: unidades_actividades';
create unique index if not exists tshare_activity_units_uidx
  on tshare_activity_units (activity_id, unit_id);

create table if not exists tshare_activity_sections (
  id          bigint generated by default as identity primary key,
  activity_id bigint not null references tshare_activities (id) on delete cascade,
  section_id  bigint not null references tshare_sections (id) on delete cascade,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_activity_sections is 'Legacy: actividades_secciones';
create unique index if not exists tshare_activity_sections_uidx
  on tshare_activity_sections (activity_id, section_id);

create table if not exists tshare_activity_skills (
  id          bigint generated by default as identity primary key,
  activity_id bigint not null references tshare_activities (id) on delete cascade,
  skill_id    bigint not null references tshare_skills (id) on delete cascade,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_activity_skills is
  'Legacy: actividades_habilidades — its nombre/descripcion columns only repeated the skill row and are dropped.';
create unique index if not exists tshare_activity_skills_uidx
  on tshare_activity_skills (activity_id, skill_id);

create table if not exists tshare_activity_resources (
  id               bigint generated by default as identity primary key,
  activity_id      bigint not null references tshare_activities (id) on delete cascade,
  resource_type_id bigint references tshare_resource_types (id) on delete set null,
  name             text not null default '',
  external_url     text,
  file_key         text,
  file_url         text,
  deleted_at       timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
comment on table tshare_activity_resources is
  'Legacy: recursos — archivo -> file_key. archivo_public only restated the key under Laravel''s /storage prefix.';
create index if not exists tshare_activity_resources_activity_idx
  on tshare_activity_resources (activity_id);

create table if not exists tshare_activity_instructions (
  id          bigint generated by default as identity primary key,
  activity_id bigint not null references tshare_activities (id) on delete cascade,
  name        text not null default '',
  body        text,
  external_url text,
  file_key    text,
  file_url    text,
  deleted_at  timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_activity_instructions is
  'Legacy: instrucciones — descripcion -> body. These are the ordered steps of the class.';
create index if not exists tshare_activity_instructions_activity_idx
  on tshare_activity_instructions (activity_id, id);

create table if not exists tshare_activity_materials (
  id           bigint generated by default as identity primary key,
  activity_id  bigint not null references tshare_activities (id) on delete cascade,
  name         text not null default '',
  external_url text,
  file_key     text,
  file_url     text,
  deleted_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
comment on table tshare_activity_materials is
  'Legacy: materiales — its apellido column was empty in every row and is dropped.';
create index if not exists tshare_activity_materials_activity_idx
  on tshare_activity_materials (activity_id);

create table if not exists tshare_saved_activities (
  id          bigint generated by default as identity primary key,
  activity_id bigint not null references tshare_activities (id) on delete cascade,
  user_id     bigint not null references tshare_users (id) on delete cascade,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_saved_activities is 'Legacy: actividades_guardadas';
create unique index if not exists tshare_saved_activities_uidx
  on tshare_saved_activities (activity_id, user_id);
create index if not exists tshare_saved_activities_user_idx on tshare_saved_activities (user_id);

create table if not exists tshare_activity_downloads (
  id          bigint generated by default as identity primary key,
  activity_id bigint not null references tshare_activities (id) on delete cascade,
  user_id     bigint not null references tshare_users (id) on delete cascade,
  quantity    int not null default 1,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_activity_downloads is
  'Legacy: actividades_descargadas — one row per (activity, user) with a running count';
create unique index if not exists tshare_activity_downloads_uidx
  on tshare_activity_downloads (activity_id, user_id);
create index if not exists tshare_activity_downloads_user_idx on tshare_activity_downloads (user_id);

create table if not exists tshare_activity_authorizations (
  id          bigint generated by default as identity primary key,
  activity_id bigint not null references tshare_activities (id) on delete cascade,
  user_id     bigint not null references tshare_users (id) on delete cascade,
  is_granted  boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_activity_authorizations is
  'Legacy: user_autoriza_actividad — the author letting another teacher edit a copy';
create index if not exists tshare_activity_authorizations_activity_idx
  on tshare_activity_authorizations (activity_id);
create index if not exists tshare_activity_authorizations_user_idx
  on tshare_activity_authorizations (user_id);

create table if not exists tshare_comments (
  id          bigint generated by default as identity primary key,
  activity_id bigint not null references tshare_activities (id) on delete cascade,
  user_id     bigint not null references tshare_users (id) on delete cascade,
  body        text not null default '',
  rating      numeric(3, 2),
  is_published boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_comments is 'Legacy: comentarios — comentario -> body, puntaje -> rating, status -> is_published';
create index if not exists tshare_comments_activity_idx on tshare_comments (activity_id, created_at desc);
create index if not exists tshare_comments_user_idx on tshare_comments (user_id);

create table if not exists tshare_comment_reactions (
  id         bigint generated by default as identity primary key,
  comment_id bigint not null references tshare_comments (id) on delete cascade,
  user_id    bigint not null references tshare_users (id) on delete cascade,
  body       text,
  is_comment boolean not null default false,
  is_like    boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table tshare_comment_reactions is 'Legacy: reactions — a like or a reply on a comment';
create index if not exists tshare_comment_reactions_comment_idx on tshare_comment_reactions (comment_id);

-- -----------------------------------------------------------------------------
-- Messaging, notifications, events
-- -----------------------------------------------------------------------------

create table if not exists tshare_messages (
  id           bigint generated by default as identity primary key,
  sender_id    bigint not null references tshare_users (id) on delete cascade,
  recipient_id bigint not null references tshare_users (id) on delete cascade,
  body         text not null default '',
  is_read      boolean not null default false,
  thread_hash  text,
  deleted_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
comment on table tshare_messages is 'Legacy: users_mensajes — de -> sender_id, para -> recipient_id, leido -> is_read';
create index if not exists tshare_messages_recipient_idx on tshare_messages (recipient_id, created_at desc);
create index if not exists tshare_messages_thread_idx on tshare_messages (thread_hash);

create table if not exists tshare_notifications (
  id         uuid primary key default gen_random_uuid(),
  user_id    bigint references tshare_users (id) on delete cascade,
  type       text not null,
  data       jsonb not null default '{}'::jsonb,
  read_at    timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table tshare_notifications is
  'Legacy: notifications. The Laravel morph (notifiable_type/notifiable_id) only ever pointed at users, so it collapses to user_id; `type` is normalised from App\\Notifications\\* to a snake_case name.';
create index if not exists tshare_notifications_user_idx
  on tshare_notifications (user_id, created_at desc);
create index if not exists tshare_notifications_unread_idx
  on tshare_notifications (user_id) where read_at is null;

create table if not exists tshare_events (
  id          bigint generated by default as identity primary key,
  user_id     bigint not null references tshare_users (id) on delete cascade,
  name        text not null,
  description text,
  event_at    timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_events is 'Legacy: eventos — fecha_evento -> event_at';
create index if not exists tshare_events_user_idx on tshare_events (user_id);

create table if not exists tshare_newsletter_subscribers (
  id          bigint generated by default as identity primary key,
  email       citext not null,
  first_name  text,
  last_name   text,
  emails_sent int not null default 0,
  attempts    int not null default 0,
  deleted_at  timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table tshare_newsletter_subscribers is
  'Legacy: subscriptores — correo_enviado -> emails_sent, intentos -> attempts';
create unique index if not exists tshare_newsletter_subscribers_email_uidx
  on tshare_newsletter_subscribers (email);

-- -----------------------------------------------------------------------------
-- Billing (Transbank / Webpay)
-- -----------------------------------------------------------------------------

create table if not exists tshare_plans (
  id            bigint generated by default as identity primary key,
  name          text,
  price         int,
  duration_days int,
  deleted_at    timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
comment on table tshare_plans is 'Legacy: subscripcion — valor -> price, duracion -> duration_days';

create table if not exists tshare_plan_features (
  id         bigint generated by default as identity primary key,
  plan_id    bigint references tshare_plans (id) on delete cascade,
  item       text,
  value      text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table tshare_plan_features is 'Legacy: subscripcion_detalle';
create index if not exists tshare_plan_features_plan_idx on tshare_plan_features (plan_id);

create table if not exists tshare_plan_roles (
  id         bigint generated by default as identity primary key,
  plan_id    bigint not null references tshare_plans (id) on delete cascade,
  role_id    bigint not null references tshare_roles (id) on delete cascade,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table tshare_plan_roles is 'Legacy: subscripcion_rol — the role a plan grants';
create unique index if not exists tshare_plan_roles_uidx on tshare_plan_roles (plan_id, role_id);

create table if not exists tshare_payments (
  id                 bigint generated by default as identity primary key,
  user_id            bigint not null references tshare_users (id) on delete cascade,
  order_number       int,
  amount_clp         int,
  detail             text,
  accounting_date    text,
  buy_order          text,
  card_last4         text,
  card_expiration    text,
  authorization_code text,
  payment_type_code  text,
  response_code      int,
  installments       text,
  amount             text,
  commerce_code      text,
  session_id         text,
  transaction_date   timestamptz,
  vci                text,
  token_ws           text,
  deleted_at         timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
comment on table tshare_payments is
  'Legacy: tbk_compra — Transbank Webpay transactions. orden_compra -> order_number, valor -> amount_clp, cardNumber -> card_last4.';
create index if not exists tshare_payments_user_idx on tshare_payments (user_id, created_at desc);

create table if not exists tshare_purchase_items (
  id         bigint generated by default as identity primary key,
  payment_id bigint not null references tshare_payments (id) on delete cascade,
  plan_id    bigint references tshare_plans (id) on delete set null,
  type       text,
  amount     int,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table tshare_purchase_items is 'Legacy: productos_compra — tipo -> type, valor -> amount';
create index if not exists tshare_purchase_items_payment_idx on tshare_purchase_items (payment_id);

-- -----------------------------------------------------------------------------
-- Activity counters
-- -----------------------------------------------------------------------------

create or replace function tshare_bump_saved_count()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    update tshare_activities set saved_count = saved_count + 1 where id = new.activity_id;
  elsif tg_op = 'DELETE' then
    update tshare_activities set saved_count = greatest(saved_count - 1, 0) where id = old.activity_id;
  end if;
  return null;
end;
$$;

create or replace function tshare_bump_download_count()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    update tshare_activities set download_count = download_count + new.quantity
      where id = new.activity_id;
  elsif tg_op = 'UPDATE' then
    update tshare_activities set download_count = greatest(download_count + new.quantity - old.quantity, 0)
      where id = new.activity_id;
  elsif tg_op = 'DELETE' then
    update tshare_activities set download_count = greatest(download_count - old.quantity, 0)
      where id = old.activity_id;
  end if;
  return null;
end;
$$;

drop trigger if exists tshare_saved_activities_count on tshare_saved_activities;
create trigger tshare_saved_activities_count
  after insert or delete on tshare_saved_activities
  for each row execute function tshare_bump_saved_count();

drop trigger if exists tshare_activity_downloads_count on tshare_activity_downloads;
create trigger tshare_activity_downloads_count
  after insert or update or delete on tshare_activity_downloads
  for each row execute function tshare_bump_download_count();

-- Recomputes both counters from the source tables. The import upserts rows,
-- which would otherwise let the triggers double-count on a re-run.
create or replace function tshare_refresh_activity_counters()
returns void
language sql
security definer
set search_path = public
as $$
  update tshare_activities a
  set saved_count =
        (select count(*)::int from tshare_saved_activities s where s.activity_id = a.id),
      download_count =
        (select coalesce(sum(d.quantity), 0)::int from tshare_activity_downloads d
         where d.activity_id = a.id);
$$;

comment on function tshare_refresh_activity_counters() is
  'Recomputes tshare_activities.saved_count / download_count from their source tables.';

-- -----------------------------------------------------------------------------
-- Loader helpers
-- -----------------------------------------------------------------------------

-- The import writes legacy ids explicitly, which leaves every identity sequence
-- sitting at 1. This pushes each one past the highest id it now holds, so the
-- first row the app inserts does not collide. `db/scripts/migrate.ts` calls it
-- through PostgREST once the load finishes.
create or replace function tshare_reset_sequences()
returns table (table_name text, next_value bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  rec record;
  seq text;
  maxid bigint;
begin
  for rec in
    select c.relname::text as tbl
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'r' and c.relname like 'tshare\_%'
    order by c.relname
  loop
    seq := pg_get_serial_sequence('public.' || quote_ident(rec.tbl), 'id');
    continue when seq is null;
    execute format('select coalesce(max(id), 0) from public.%I', rec.tbl) into maxid;
    perform setval(seq, greatest(maxid, 1), maxid > 0);
    table_name := rec.tbl;
    next_value := maxid + 1;
    return next;
  end loop;
end;
$$;

comment on function tshare_reset_sequences() is
  'Re-seeds every tshare_* identity sequence past the largest id in its table. Run after a data import.';

commit;
